export default [
  {
    name: 'model',
    texIndex: -1,
    type: 'glbModel',
    path: '/Public/rvModel.glb',
  },
  {
    name: 'texture0',
    texIndex: 0,
    type: 'image',
    path: '/Public/texture0.png',
  },
  // {
  //   name: 'texture1',
  //   texIndex: 1,
  //   type: 'image',
  //   path: '/Public/texture1.png',
  // },
  // {
  //   name: 'texture2',
  //   texIndex: 2,
  //   type: 'image',
  //   path: '/Public/texture2.png',
  // },
  // {
  //   name: 'texture3',
  //   texIndex: 3,
  //   type: 'image',
  //   path: '/Public/texture3.png',
  // },
  // {
  //   name: 'texture4',
  //   texIndex: 4,
  //   type: 'image',
  //   path: '/Public/texture4.png',
  // },
  // {
  //   name: 'texture5',
  //   texIndex: 5,
  //   type: 'image',
  //   path: '/Public/texture5.png',
  // },
  // {
  //   name: 'texture6',
  //   texIndex: 6,
  //   type: 'image',
  //   path: '/Public/texture6.png',
  // },
  // {
  //   name: 'texture7',
  //   texIndex: 7,
  //   type: 'image',
  //   path: '/Public/texture7.png',
  // },
  // {
  //   name: 'texture8',
  //   texIndex: 8,
  //   type: 'image',
  //   path: '/Public/texture8.png',
  // },

  // {
  //   name: 'texture9',
  //   texIndex: 9,
  //   type: 'image',
  //   path: '/Public/texture9.png',
  // },
  // {
  //   name: 'texture10',
  //   texIndex: 10,
  //   type: 'image',
  //   path: '/Public/texture10.png',
  // },
  // {
  //   name: 'texture11',
  //   texIndex: 11,
  //   type: 'image',
  //   path: '/Public/texture11.png',
  // },
  // {
  //   name: 'texture12',
  //   texIndex: 12,
  //   type: 'image',
  //   path: '/Public/texture12.png',
  // },
  // {
  //   name: 'texture13',
  //   texIndex: 13,
  //   type: 'image',
  //   path: '/Public/texture13.png',
  // },
  // {
  //   name: 'texture14',
  //   texIndex: 14,
  //   type: 'image',
  //   path: '/Public/texture14.png',
  // },
  // {
  //   name: 'texture15',
  //   texIndex: 15,
  //   type: 'image',
  //   path: '/Public/texture15.png',
  // },
];
